# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pet Store API Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run test cases
      run: mvn -B clean verify --file pom.xml
    - name: Publish Test Report
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
        name: 'test-report'
        path: target/site/*
